/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef backup_interface_CONSTANTS_H
#define backup_interface_CONSTANTS_H

#include "backup_interface_types.h"



class backup_interfaceConstants {
 public:
  backup_interfaceConstants();

};

extern const backup_interfaceConstants g_backup_interface_constants;



#endif
