/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "backup_interface_constants.h"



const backup_interfaceConstants g_backup_interface_constants;

backup_interfaceConstants::backup_interfaceConstants() {
}



