// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "BackupService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class BackupServiceHandler : virtual public BackupServiceIf {
 public:
  BackupServiceHandler() {
    // Your initialization goes here
  }

  int64_t backup(const Operation::type op, const int64_t param1, const int64_t param2) {
    // Your implementation goes here
    printf("backup\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<BackupServiceHandler> handler(new BackupServiceHandler());
  shared_ptr<TProcessor> processor(new BackupServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

