/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "backup_interface_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _kOperationValues[] = {
  Operation::ADD_NODE,
  Operation::REMOVE_NODE,
  Operation::ADD_EDGE,
  Operation::REMOVE_EDGE,
  Operation::GET_NODE
};
const char* _kOperationNames[] = {
  "ADD_NODE",
  "REMOVE_NODE",
  "ADD_EDGE",
  "REMOVE_EDGE",
  "GET_NODE"
};
const std::map<int, const char*> _Operation_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kOperationValues, _kOperationNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


